name: KnockIT
main: de.doppelkool.knockit.Main
version: 1.0.0-SNAP
description: KnockbackFFA-Remake by doppelkool, remade from CoredTV
author: doppelkool
api-version: 1.20
website: https://www.github.com/doppelkool
libraries:
  - com.zaxxer:HikariCP:5.1.0
commands:
  stats:
    usage: /<command>
    description: Displays the stats of the player